FROM python:3.11

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project code
COPY . .

# Set environment variables
ENV DJANGO_SETTINGS_MODULE=raslanAPI.settings

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000
EXPOSE 5678

ENTRYPOINT ["/entrypoint.sh"]

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]