#Use the official Node.js base image
FROM node:18

WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

COPY . .

#Command to to start raslan-ui App
CMD [ "npm", "start" ]